"""empty message

Revision ID: 77596e27ce21
Revises: 4d6c13abd3b8
Create Date: 2023-03-06 00:43:06.700179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77596e27ce21'
down_revision = '4d6c13abd3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project1', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
